# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  E1:
    has_velocity_limits: true
    max_velocity: 1.85
    has_acceleration_limits: false
    max_acceleration: 0
  E2:
    has_velocity_limits: true
    max_velocity: 1.85
    has_acceleration_limits: false
    max_acceleration: 0
  S1:
    has_velocity_limits: true
    max_velocity: 0.85
    has_acceleration_limits: false
    max_acceleration: 0
  S2:
    has_velocity_limits: true
    max_velocity: 0.85
    has_acceleration_limits: false
    max_acceleration: 0
  W1:
    has_velocity_limits: true
    max_velocity: 1.85
    has_acceleration_limits: false
    max_acceleration: 0
  W2:
    has_velocity_limits: true
    max_velocity: 5.65486677646
    has_acceleration_limits: false
    max_acceleration: 0
  W3:
    has_velocity_limits: true
    max_velocity: 5.65486677646
    has_acceleration_limits: false
    max_acceleration: 0
  finger_joint_1:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0
  finger_joint_2:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: false
    max_acceleration: 0